reward:
  invite: 300
  # 获取打开奖励页面的间隔-单位秒
  interval: 3600
  # 每次可选择的物品
  choose: 3
  # 每个选择的物品数量
  stack: 64
  # 物品数量
  item:
    - STONE
    - DIRT
    - SAND
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - CHERRY_LOG
    - DARK_OAK_LOG
    - MANGROVE_LOG
    - OAK_WOOD
    - SPRUCE_WOOD
    - BIRCH_WOOD
    - JUNGLE_WOOD
    - ACACIA_WOOD

  week_daily:
    Thursday:
      message: '<green>SW疯狂星期四,V你%sSW！'
      reward:
        type: 'MONEY'
        value: 50
    Other:
      message: '<white>日常登录成功,随机获取了%s SW日常登录奖励'
      reward:
        type: 'RANDOM'
        value: '30-99'
